name:                pandoc-hide-codeblocks
version:             0.3.0.0
github:              "mgajda/pandoc-hide-codeblocks"
license:             Apache
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "Copyright Input Output HK 2019"

extra-source-files:
- README.md
- ChangeLog.md
- NOTICE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgajda/pandoc-hide-codeblocks#readme>

dependencies:
- base >= 4.7 && < 5
ghc-options:
- -fwarn-unused-binds
- -fwarn-unused-imports

# This is a build tool for documentation - a pandoc filter.
executables:
  pandoc-hide-codeblocks:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - pandoc-types

