name:                latency-sim
version:             0.2.0.0
github:              "mgajda/latency-sim"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@gmail.com"
copyright:           "Copyright Input Output HK 2019"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mgajda/latency-sim#readme>

dependencies:
- base >= 4.7 && < 5
ghc-options:
- -pgmL markdown-unlit
- -fwarn-unused-binds
- -fwarn-unused-imports

library:
  source-dirs: src
  dependencies:
    - matrix
    - mwc-random
    - QuickCheck
    - statistics
    - hspec
    - validity
    - genvalidity
    - http-client
    - uniplate
  build-tools:
    - markdown-unlit
    - pandoc
    - pandoc-citeproc
    - pandoc-filter-graphviz
    - pandoc-hide-codeblocks

tests:
  latency-sim-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latency-sim
    - hspec
    - hspec-expectations
    - statistics
    - QuickCheck
    - validity
    - genvalidity
    - genvalidity-hspec
    - genvalidity-property
    - matrix
    build-tools:
    - hspec-discover
    - markdown-unlit
    - pandoc-filter-graphviz
    - pandoc-hide-codeblocks
  simulation-test:
    main:                SimulationTest.lhs
    source-dirs:
      - test
      - sim
    other-modules: LatencySpec ProbabilitySpec SeriesSpec DelaySpec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latency-sim
    - hspec
    - hspec-expectations
    - statistics
    - QuickCheck
    - validity
    - genvalidity
    - genvalidity-hspec
    - genvalidity-property
    - matrix
    build-tools:
    - hspec-discover
    - markdown-unlit
    - pandoc-hide-codeblocks

