name:                latency-sim
version:             0.1.0.0
github:              "mgajda/latency-sim"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@gmail.com"
copyright:           "Copyright Input Output HK 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgajda/latency-sim#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -pgmL markdown-unlit
  dependencies:
    - markdown-unlit
    - time
    - QuickCheck

executables:
  hide-codeblocks:
    main:                hide-codeblocks.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - pandoc-types

tests:
  latency-sim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latency-sim
    - QuickCheck
    - hspec
