name:                latency-sim
version:             0.2.0.0
github:              "mgajda/latency-sim"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@gmail.com"
copyright:           "Copyright Input Output HK 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgajda/latency-sim#readme>

dependencies:
- base >= 4.7 && < 5
ghc-options:
- -pgmL markdown-unlit

library:
  source-dirs: src
  dependencies:
    - hspec
    - mwc-random
    - QuickCheck
    - statistics
  build-tools:
    - markdown-unlit
    - pandoc
    - pandoc-citeproc

# This is a build tool for documentation - a pandoc filter.
executables:
  hide-codeblocks:
    main:                hide-codeblocks.hs
    source-dirs:         app/pandoc-hide-codeblocks
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - pandoc-types

tests:
  latency-sim-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - latency-sim
    - statistics
    - QuickCheck
    build-tools:
    - hspec-discover
    - markdown-unlit

