# Acknowledgments

Michał started writing, since the task seemed so easy to do within a month
or two.
Duncan made sure that discussion constructively proceeds
for reasonable amount of time,
and everybody follows. Marcin made sure that nobody breaks the family
glasses, and reviewed code carefully.
Lars provided excellent counterexamples for distributivity, and helpful discussions.
