
# Schedule
## Milestones proposed

1. Possible metrics explored
    * mathematical characterization
    * implementation
    * algebraic property exploration
2. Comparison with other graph metrics
3. Properties of the metric
      * enumeration of desired or expected properties
      * derive algebra of the chosen metric
4. Implementation of the metric
      * datatype for $∆Q(t)$ and $∆R(t)$.
        and optimization of reduction of $∆Q(t)$
        computation.
      * computing $∆Q(t)$ and $∆R(t)$ curve for random network
      connections.
5. Comparison with other metrics used for graph and network research
      * visualizing one or multiple distributions
      * assertions about classical graph algorithms vs rates
      * computing metrics random networks

## Desired outcomes:
* mathematical theory and statistical tool for modelling tool latencies
  over high capacity networks
* statistical assessments of these policies under adverse scenarios

## Future plans:
* proof that our policies are almost-optimal after convergence
* expand the theory into capacity-limited networks
* apply it to reason about latency of other protocols within Cardano
* modelling a most adverse scenario [@ProgrammingSatan]

